\\ kubectl commands
kubectl get pods
kubectl get pods -l='tier=db'
kubectl run nginx --image=nginx
kubectl describe pod nginx
kubectl run redis --image=redis123 --dry-run:client -o yml > pod-difinition.yaml
kubectl apply -f pod-difinition.yaml
kubectl edit pod [pod_name]
kubectl run redis --image=redis --port=8080 --expose=true

как поменять значения в под командой?


\\ pod-difinition.yaml file
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - image: redis123
      name: redis




