##create pod in namespace that will run specific command,
# use configmap for env var and write results to specific path
# on mounted volume

# configmap create
# kubectl create configmap time-config --namespace xfusion --from-literal=TIME_FREQ=3

# check the results
# kubectl exec time-check --namespace xfusion -- cat /opt/dba/time/time-check.log

apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: xfusion
spec:
  containers:
    - image: busybox:latest
      name: time-check
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do date; sleep $TIME_FREQ; done > /opt/dba/time/time-check.log",
        ]
      envFrom:
        - configMapRef:
            name: time-config
      volumeMounts:
        - name: log-volume
          mountPath: /opt/dba/time
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"
  volumes:
    - name: log-volume
      emptyDir: {}
