\\ taints & tolerations
kubectl taint node [node-name] env=dev:NoSchedule

kubectl describe node [node-name]
! check taints

kubectl taint node [node-name] env=dev:NoSchedule-
! to remove taint

\\ pod difinition with tolerations
apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - image: nginx
    name: name-container
  tolerations:
  - key: "env"
    value: "dev"
    operator: "Equal"
    effect: "NoSchedule"

\\ node affinity
types
requiredDuringSchedulingIgnoredDuringExecution:
preferredDuringSchedulingIgnoredDuringExecution:
requiredDuringSchedulingRequiredDuringExecution:

apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - antarctica-east1
            - antarctica-west1
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:2.0
