\\ Persistent Volume

- kubectl get pv
- kubectl describe pv

\\ yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: <Size>
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data

\\ Persistent Volume Claim

- kubectl get pvc
- kubectl describe pvc

\\ yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: <Size>
  accessModes:
    - ReadWriteOnce
  storageClassName: [sc-name]


