\\ taints & tolerations
kubectl taint node [node-name] env=dev:NoSchedule

kubectl describe node [node-name]
! check taints

kubectl taint node [node-name] env=dev:NoSchedule-
! to remove taint

// pod difinition
apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - image: nginx
    name: name-container
  tolerations:
  - key: "env"
    value: "dev"
    operator: "Equal"
    effect: "NoSchedule"
