#task to create a job with specific config

apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-datacenter
spec:
  template:
    metadata:
      name: countdown-datacenter #good to know that template has own metadata section
    spec:
      containers:
      - name: container-countdown-datacenter
        image: centos:latest
        command:
        - /bin/sh
        - c-
        - for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done
      restartPolicy: Never
  backoffLimit: 4