\\ commands for replicaset
kubectl get replicaset
kubectl get rs
kubectl create replicaset -f replicaset-difinition.yaml
kubectl describe replicaset [name of replicaset]
kubectl edit replicaset [name of replicaset]
kubectl scale replicaset [name of replicaset] --replicas=6


\\ yaml file for replicaset
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3



