apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-color
data:
  {{- if eq .Values.environment "production" }}
  APP_COLOR: pink
  {{- else if eq .Values.environment "development" }}
  APP_COLOR: darkblue
  {{- else }}
  APP_COLOR: green
  {{- end }}