apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      containers:
      - name: myapp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }} #combine values
        ports:
          - name: http
            containerPort: 80
            protocol: TCP