apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-nginx-svc-helpers
  labels:
    {{- template "labels" . }} #using labels from _helpers.tpl
    #{{- include "labels" . | indent 2 }} - add and moves lines with two spaces then adding it to the code
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http